language: go

go:
  - "1.x"
  - "1.12"

env:
  - GO111MODULE=on

install:
  - go mod download

before_script:
  - wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.16.0

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - bin/golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)