language: go

go:
  - "1.x"
  - "1.12"
  - "1.11"

env:
  - GO111MODULE=on

before_script:
  - wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.16.0

script:
  - go test ./...
  - golangci-lint run --enable-all