language: go

go:
  - "1.x"
  - "1.12"

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint golangci-lint run
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
